### ISSUE TITLE
Warning affecting functionality of the tool (2)

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/ASSET#17]
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Probably related to #4

**Comment by abishek2094** [comment]
Fixed with commit - 8effa8d6db5a06441934abe8f911f72287e19852
