### ISSUE TITLE
Need to implement exporting and importing of workflows

### ISSUE THREAD

**Issue by beareye** [KnowledgeCaptureAndDiscovery/ASSET#3]

**Comment by dgarijo** [comment]
Exporting works, as far as I know

**Comment by beareye** [comment]
ok my bad looks like the server wasnt running properly on my system

**Comment by dgarijo** [comment]
No worries.
Importing workflows is not yet implemented, so the issue is still half
valid.

2018-06-12 17:10 GMT-07:00 Jeffrey Wang <notifications@github.com>:
