### ISSUE TITLE
Details table is too editable

### ISSUE THREAD

**Issue by mistyblue17** [KnowledgeCaptureAndDiscovery/ASSET#30]
Each tool has a table to describe the tool, which is great! However, the column of the table with the field titles should not be able to be edited. Also it should be scaled to fit the titles so that more space is left for the blank column to be filled in. At first, I didn't realize that there were 2 columns so I added the details in the same cells as the titles.

**Comment by beareye** [comment]
This is a good suggestion and i will work on this. What do u think we should do about the adding new properties feature? Was it unnecessary?

**Comment by mistyblue17** [comment]
No, I think the new properties feature is good. I didn't fully realize it's potential until I looked at Perry's example where he added software versions and such.
