### ISSUE TITLE
Text will overlap from different nodes

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/ASSET#33]
When displaying text from different nodes, it will overlap (see image)
![overlap](https://user-images.githubusercontent.com/1520666/43609594-5443c230-9659-11e8-876f-61e22645af9b.png)

This makes reading big graphs a little difficult to read.
Probably text should be made smaller when the zoom is out. Also, text could show "..." when title is too long, while showing full text when hovering the mouse.

**Comment by abishek2094** [comment]
Added with commit c6ac3ef7eaee122f7c0097929dd2d7e3902a7dbc
