### ISSUE TITLE
When adding space to property, if it is the last character it makes weird symbols

### ISSUE THREAD

**Issue by reginawang3495** [KnowledgeCaptureAndDiscovery/ASSET#38]
![image](https://user-images.githubusercontent.com/29292203/43738777-acdc3034-997a-11e8-8a57-f6342bb38803.png)

**Comment by dgarijo** [comment]
ah, that is the html representation of a blank space (non-breaker space, nbsp). Nice catch!

**Comment by abishek2094** [comment]
Fixed with Commit : c6ac3ef7eaee122f7c0097929dd2d7e3902a7dbc
