### ISSUE TITLE
Cannot add properties to examples arrows.

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/ASSET#62]
If you load an example and try to create an arrow with text, this error happens:

![Screen Shot 2021-03-15 at 19 02 54](https://user-images.githubusercontent.com/15269912/111227278-13a9a780-85c1-11eb-8828-66aa7cb54170.png)

**Comment by dgarijo** [comment]
@wangyira this issue affects usability and should have the highest priority
